Update pretrained.py
Here i am fixing the error "AttributeError: module 'keras.utils' has no attribute 'get_file' " by adding some simple lines of code like importing the tensorflow as tf because the keras.utils.get_file has been changed to tf.keras.utils.get_file in latest versions . Thank you :)